ASSETS = [
    "BTCUSDT", "ETHUSDT", "BNBUSDT", "SOLUSDT", "AVAXUSDT",
    "ADAUSDT", "DOTUSDT", "MATICUSDT", "ATOMUSDT", "LTCUSDT",
    "UNIUSDT", "AAVEUSDT", "LINKUSDT", "INJUSDT", "RUNEUSDT",
    "SUIUSDT", "OPUSDT", "SEIUSDT", "TIAUSDT", "PYTHUSDT",
    "ICPUSDT", "TONUSDT", "WLDUSDT", "ENAUSDT", "ONDOUSDT", "ASTRUSDT",
    "FETUSDT", "RNDRUSDT", "TAOUSDT", "EIGENUSDT", "KAITOUSDT", "ETHFIUSDT",
    "DOGEUSDT", "SHIBUSDT", "PEPEUSDT", "BONKUSDT", "FLOKIUSDT",
    "WIFUSDT", "PENGUUSDT",
    "FILUSDT", "HBARUSDT", "VETUSDT", "IOTAUSDT", "JUPUSDT",
    "SANDUSDT", "SYRUPUSDT", "ETCUSDT",
]
